_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
clip_range:
    value: 0.3066692385092978
entropy_coefficient:
    value: 0.009240550350090047
learning_rate:
    value: 0.0008413033782337434
