_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
clip_range:
    value: 0.33996166514448944
entropy_coefficient:
    value: 0.016967225373502336
learning_rate:
    value: 0.0005882520842404232
