_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.30788319690654214
entropy_coefficient:
    value: 0.010918831811146845
gae_lambda:
    value: 0.9707611053962252
gamma:
    value: 0.9796335065319588
learning_rate:
    value: 0.0006187354220607132
n_steps:
    value: 4096
