_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
clip_range:
    value: 0.2505022791566265
entropy_coefficient:
    value: 0.019234685461589563
gae_lambda:
    value: 0.9869716702457992
gamma:
    value: 0.9707678287795984
learning_rate:
    value: 0.0005292228507331433
n_steps:
    value: 2048
