_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
clip_range:
    value: 0.29953240641330514
entropy_coefficient:
    value: 0.009034739246985096
gae_lambda:
    value: 0.9880728056845748
gamma:
    value: 0.9760355367887352
learning_rate:
    value: 0.0006313942093791253
n_steps:
    value: 4096
