_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
clip_range:
    value: 0.33799972081508717
entropy_coefficient:
    value: 0.007213641072476733
gae_lambda:
    value: 0.979620946938066
gamma:
    value: 0.983397217911532
learning_rate:
    value: 0.000789019291679629
n_steps:
    value: 4096
