_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.2684464665696033
entropy_coefficient:
    value: 0.018730979573051875
gae_lambda:
    value: 0.97351103988009
gamma:
    value: 0.970629981969082
learning_rate:
    value: 0.0009438792972084432
n_steps:
    value: 2048
