_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.30760522103999294
entropy_coefficient:
    value: 0.01650478262118377
gae_lambda:
    value: 0.9569648549841776
gamma:
    value: 0.977554462747289
learning_rate:
    value: 0.0008558719158307125
n_steps:
    value: 2048
