_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
                - 55
            "4": 3.8.20
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
clip_range:
    value: 0.34191105521476417
entropy_coefficient:
    value: 0.018544346928961453
learning_rate:
    value: 0.0009091016725896092
