_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
clip_range:
    value: 0.2734690968332388
entropy_coefficient:
    value: 0.007733349837848267
gae_lambda:
    value: 0.972715517572282
gamma:
    value: 0.9732895844303472
learning_rate:
    value: 0.0006458648197710841
n_steps:
    value: 2048
