_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.29960550952813453
entropy_coefficient:
    value: 0.016184463676716193
gae_lambda:
    value: 0.9748081993629228
gamma:
    value: 0.9764819449091392
learning_rate:
    value: 0.0006725495202063207
n_steps:
    value: 2048
