_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.27554324372649963
entropy_coefficient:
    value: 0.00926756449638325
gae_lambda:
    value: 0.9511851948430664
gamma:
    value: 0.9709873585962298
learning_rate:
    value: 0.0006676863739315717
n_steps:
    value: 4096
