_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 128
clip_range:
    value: 0.33285628206002466
entropy_coefficient:
    value: 0.017475769109612724
gae_lambda:
    value: 0.9694306483531342
gamma:
    value: 0.9864559579011204
learning_rate:
    value: 0.0008410748512928987
n_steps:
    value: 2048
