_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.9.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 55
                - 61
            "4": 3.9.5
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
clip_range:
    value: 0.3421008319931056
entropy_coefficient:
    value: 0.01558183858874878
gae_lambda:
    value: 0.9637207850730674
gamma:
    value: 0.9727546810909238
learning_rate:
    value: 0.0006455938919619777
n_steps:
    value: 2048
